#!/bin/bash
#PBS -N caseTests
#PBS -A P28100045
#PBS -l walltime=12:00:00
#PBS -q main
#PBS -l select=1:ncpus=128:mpiprocs=8:ompthreads=16
#PBS -j oe
#PBS -m abe

# NOTE: The user account must be specified on the qsub command line with the
# -A option,
# KAIJUROOTDIR and MODULE_LIST must be set as transferred environment
# variables on the qsub command line.
# Example qsub command:
# qsub -A P28100045 -v $HOME/kaiju,MODULE_LIST='module1 module2 ...'

echo "Job $PBS_JOBID started at `date` on `hostname` in directory `pwd`."

echo 'Setting up MAGE environment.'
source $KAIJUROOTDIR/scripts/setupEnvironment.sh

echo 'Loading modules.'
module --force purge
module load $MODULE_LIST
echo 'The following modules are loaded:'
module list

echo 'Setting environment variables.'
MPICOMMAND="mpiexec $KAIJUHOME/scripts/preproc/pinCpuCores.sh"
export OMP_NUM_THREADS=128
export MPI_TYPE_DEPTH=32
export KMP_STACKSIZE=128M
echo 'The active environment variables are:'
printenv

echo 'Running non-MPI test cases.'
date
./caseTests >& caseTests.out
date
echo 'Non-MPI test cases complete.'
echo | tail -n 3 ./caseTests.out

echo 'Running MPI test cases.'
date
${MPICOMMAND} ./caseMpiTests >& caseMpiTests.out
date
echo 'MPI test cases complete.'
echo | tail -n 3 ./caseMpiTests.out

echo "Job $PBS_JOBID ended at `date` on `hostname` in directory `pwd`."
