#!/bin/bash
#Re-generate restart files for automated tests

#PBS -N testResGen
#PBS -l walltime=00:30:00
#PBS -q main
#PBS -j oe
#PBS -l select=4:ncpus=128:mpiprocs=2:ompthreads=64+1:ncpus=128:mpiprocs=1:ompthreads=128


#KAIJUROOTDIR=/glade/work/ewinter/mage_testing/derecho/kaiju/ewinter-move_testing_to_derecho/kaiju
source $KAIJUROOTDIR/scripts/setupEnvironment.sh

module --force purge
# module load ncarenv/23.06
# module load cmake/3.26.3
# module load craype/2.7.20
# module load intel/2023.0.0
# module load ncarcompilers/1.0.0
# module load cray-mpich/8.1.25
# module load hdf5-mpi/1.12.2
# module load mkl/2023.0.0
module load $MODULE_LIST
module list

export MPICOMMAND="mpiexec $KAIJUHOME/scripts/preproc/pinCpuCores.sh"
export OMP_NUM_THREADS=128
export MPI_TYPE_DEPTH=32
export KMP_STACKSIZE=128M

echo "Running on host `hostname` on `date`"
echo "PWD = $PWD"

$MPICOMMAND ./voltron_mpi.x geo_mpi.xml > geo_mpi.out

echo "Finished run on `date`"
