#!/bin/bash
#PBS -N caseTests
#PBS -A UJHB0019
#PBS -j oe
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=128:mpiprocs=8:ompthreads=16
#PBS -m abe

KAIJUROOTDIR=/glade/work/ewinter/mage_testing/derecho/kaiju/ewinter-move_testing_to_derecho/kaiju
source $KAIJUROOTDIR/scripts/setupEnvironment.sh

module --force purge
module load ncarenv/23.06
module load cmake/3.26.3
module load craype/2.7.20
module load intel/2023.0.0
module load ncarcompilers/1.0.0
module load cray-mpich/8.1.25
module load hdf5-mpi/1.12.2
module load mkl/2023.0.0
module list

MPICOMMAND="mpiexec $KAIJUHOME/scripts/preproc/pinCpuCores.sh"
export OMP_NUM_THREADS=128
export MPI_TYPE_DEPTH=32
export KMP_STACKSIZE=128M

echo ""
echo "Running Non MPI Cases"
date
./caseTests > caseTests.out
date
echo "Non MPI Cases Complete"
echo | tail -n 3 ./caseTests.out

echo ""
echo "Running MPI Cases"
date
${MPICOMMAND} ./caseMpiTests > caseMpiTests.out
date
echo "MPI Cases Complete"
echo | tail -n 3 ./caseMpiTests.out
