#!/bin/bash
#PBS -A UJHB0015
#PBS -N nonCaseTests1
#PBS -j oe
#PBS -q regular
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=36:mpiprocs=64:ompthreads=72

source ~/.bashrc

module list
hostname
export OMP_NUM_THREADS=72
export KMP_STACKSIZE=128M
export MPI_TYPE_DEPTH=32

echo ""
echo "Running Gamera Tests"
date
./gamTests > gamTests.out
date
echo "Gamera Tests Complete"
echo | tail -n 2 ./gamTests.out

echo ""
echo "Running Remix Tests"
date
./mixTests > mixTests.out
date
echo "Remix Tests Complete"
echo | tail -n 2 ./mixTests.out

echo ""
echo "Running Voltron Tests"
date
./voltTests > voltTests.out
date
echo "Voltron Tests Complete"
echo | tail -n 2 ./voltTests.out

echo ""
echo "Running Base MPI Tests"
date
mpirun ./baseMpiTests > baseMpiTests.out
date
echo "Base MPI Tests Complete"
echo | tail -n 2 ./baseMpiTests.out

echo ""
echo "Running Gamera MPI Tests"
date
mpirun ./gamMpiTests > gamMpiTests.out
date
echo "Gamera MPI Tests Complete"
echo | tail -n 2 ./gamMpiTests.out

