{% set name = "kaipy" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 86e5f8ab19792f31be6d31d95b8afad7fafc4d76395aa1a4b4f2d2f048fe9527

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - kaipy
    - kaipy.chimp
    - kaipy.gamera
    - kaipy.gamhelio
    - kaipy.gamhelio.lib
    - kaipy.gamhelio.wsa2TDgamera
    - kaipy.gamhelio.wsa2gamera
    - kaipy.paraview
    - kaipy.rcm
    - kaipy.rcm.lambdautils
    - kaipy.rcm.lambdautils_old
    - kaipy.rcm.wmutils
    - kaipy.remix
    - kaipy.solarWind
  requires:
    - nose

about:
  home: "https://bitbucket.org/aplkaiju/kaiju/src/master/"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Postprocessing code for models in the kaiju software system"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
